export enum UserEvent {
  CreateRoom = "createRoom",
  JoinRoom = "joinRoom",
  LeaveRoom = "leaveRoom",
  StartGame = "startGame",
  SubmitPremise = "submitPremise",
  SubmitGuess = "submitGuess",
  VoteToSkip = "voteToSkip",
  SendMessage = "sendMessage",
  EndGame = "endGame",
  UpdateMaxTime = "updateMaxTime",
}

export enum GameEvent {
  RoomCreated = "roomCreated",
  RoomNotFound = "roomNotFound",
  RoomFull = "roomFull",
  RoomJoined = "roomJoined",
  PlayerJoined = "playerJoined",
  RoomLeft = "roomLeft",
  PlayerLeft = "playerLeft",
  GameStarted = "gameStarted",
  GameStateUpdated = "gameStateUpdated",
  GuesserSelected = "guesserSelected",
  PremisePlayerSelected = "premisePlayerSelected",
  PremiseSubmitted = "premiseSubmitted",
  GuessSubmitted = "guessSubmitted",
  RoundEnded = "roundEnded",
  MessageReceived = "messageReceived",
  HistoryUpdated = "historyUpdated",
  ImageGenerated = "imageGenerated",
  TimerSync = "timerSync",
  MaxTimeUpdated = "maxTimeUpdated",
  AdminChanged = "adminChanged",
  GameEnded = "gameEnded",
  VoteUpdated = "voteUpdated",
  PlayerSkipped = "playerSkipped",
  StatsUpdated = "statsUpdated",
  TurnTimeout = "TurnTimeout",
}
